# dataset
dataset: CIFAR100
half: 16

# dir
data_dir: ./data/CIFAR100/
resume: ''
save: ./model/CIFAR100/base

# model
report_freq: 5
workers: 8

# backdoor
backdoor: 50
poison_epochs: 80
target_class: apple
poison_num: 4
corruption_amp: 5.0
backdoor_start: True

# Hyperparameters
lr: 0.2
alpha: 0.05
eps: 1.0
epochs: 100
batch_size: 64

